---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  # ----------------------- OPS -----------------------
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, "2", --sequence, "4", --offset, "2", --width, "150", --preserve-quotes]
        exclude: ^.github/dependabot.yaml
#        exclude: (sops\.yaml)$
  # ----------------------- GOLANG -----------------------
  - repo: https://github.com/kahnwong/pre-commit
    rev: "3112305"
    hooks:
      - id: hadolint
        args:
          - --ignore
          - DL3025
          - --ignore
          - DL3018
          - --ignore
          - DL3027
      - id: go-build
      - id: go-fmt
      - id: go-imports
      - id: go-mod-tidy
      - id: go-vet
      - id: golangci-lint
